apiVersion: v1
kind: Service
metadata:
  name: library-management-api-service
spec:
  type: LoadBalancer
  selector:
    app: library-management-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
